<?php
echo '<div class="form-column" style="flex: 1">';
    echo '<div class="floating-label-container" style="flex: 1">';
        echo '<select id="display_time" name="display_time" class="floating-label-input" required style="background: #FFFF">';
            echo '<option value="">~</option>';
            echo '<option value="10">10 seconds</option>';
            echo '<option value="11">11 seconds</option>';
            echo '<option value="12">12 seconds</option>';
            echo '<option value="13">13 seconds</option>';
            echo '<option value="14">14 seconds</option>';
            echo '<option value="15">15 seconds</option>';
            echo '<option value="16">16 seconds</option>';
            echo '<option value="17">17 seconds</option>';
            echo '<option value="18">18 seconds</option>';
            echo '<option value="19">19 seconds</option>';
            echo '<option value="20">20 seconds</option>';
            echo '<option value="21">21 seconds</option>';
            echo '<option value="22">22 seconds</option>';
            echo '<option value="23">23 seconds</option>';
            echo '<option value="24">24 seconds</option>';
            echo '<option value="25">25 seconds</option>';
            echo '<option value="26">26 seconds</option>';
            echo '<option value="27">27 seconds</option>';
            echo '<option value="28">28 seconds</option>';
            echo '<option value="29">29 seconds</option>';
            echo '<option value="30">30 seconds</option>';
        echo '</select>';
        echo '<label for="display_time" class="floating-label">Display Time (seconds)</label>';
    echo '</div>';
    echo '<div class="floating-label-container" style="flex: 1">';
        echo '<select id="tv_account_select" name="tv_id" class="floating-label-input" style="background: #FFFF">';
            echo '<option value="">~</option>';
            echo $options_tv;
            echo '<option value="All Smart TVs">All Smart TVs</option>';
        echo '</select>';
        echo '<label for="tv_id" class="floating-label">TV Display</label>';
    echo '</div>';
echo '</div>';
echo '</div>';
?>